server:
  port: 8086
spring:
  application:
    name: rabbitMqTest1
  rabbitmq:
    host: 192.168.139.129
    #默认端口5672
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /