server:
  port: 8086
spring:
  application:
    name: rabbitMqTest1
  rabbitmq:
    host: 127.0.0.1
    #默认端口5672
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /